import {it,expect,vi,afterEach} from 'vitest';
afterEach(()=>{vi.unstubAllGlobals();vi.resetModules();});
it('keeps credentials per tab in memory and rejects cross-tenant and stale account responses',async()=>{
 let complete!:(details:chrome.webRequest.OnCompletedDetails)=>unknown;
 let capture!:(details:chrome.webRequest.OnBeforeSendHeadersDetails)=>unknown;
 let navigate!:(details:chrome.webRequest.OnBeforeRequestDetails)=>unknown;
 let removed!:(tabId:number)=>void;
 let listener!:(message:unknown,sender:chrome.runtime.MessageSender,reply:(value:unknown)=>void)=>unknown;
 const sendMessage=vi.fn(async()=>{}),storage=vi.fn();
 vi.stubGlobal('chrome',{runtime:{id:'own',onMessage:{addListener:(fn:typeof listener)=>{listener=fn;}}},tabs:{sendMessage,onRemoved:{addListener:(fn:typeof removed)=>{removed=fn;}}},webRequest:{onBeforeSendHeaders:{addListener:(fn:typeof capture)=>{capture=fn;}},onCompleted:{addListener:(fn:typeof complete)=>{complete=fn;}},onErrorOccurred:{addListener:vi.fn()},onBeforeRequest:{addListener:(fn:typeof navigate)=>{navigate=fn;}}},storage:{local:{set:storage}}});
 const fetch=vi.fn(async()=>new Response(JSON.stringify({items:[]}),{status:200}));vi.stubGlobal('fetch',fetch);
 await import('../src/magister/auth-worker');
 const sender={id:'own',url:'https://school.magister.net/#/cijfers',frameId:0,tab:{id:1} as chrome.tabs.Tab};
 const request={requestId:'test-request',url:'https://school.magister.net/api/personen/17/cijfers/laatste',tabId:1,type:'xmlhttprequest',requestHeaders:[{name:'Authorization',value:'synthetic-token'}]} as chrome.webRequest.OnBeforeSendHeadersDetails;
 const send=(s=sender)=>new Promise<unknown>(resolve=>{if(listener({protocol:'po/magister-recent'},s,resolve)!==true)resolve(null);});
 expect(await send()).toMatchObject({ok:false});expect(fetch).not.toHaveBeenCalled();
 capture(request);capture(request);expect(sendMessage).not.toHaveBeenCalled();expect(await send()).toMatchObject({ok:false});complete({requestId:request.requestId,statusCode:200} as chrome.webRequest.OnCompletedDetails);expect(sendMessage).toHaveBeenCalledTimes(1);
 expect(await send({...sender,url:'https://other.magister.net/#/cijfers'})).toMatchObject({ok:false});
 expect(await send({...sender,tab:{id:2} as chrome.tabs.Tab})).toMatchObject({ok:false});
 expect(await send({...sender,id:'foreign'})).toBeNull();
 expect(await send()).toEqual({ok:true,userId:'17',records:[]});
 expect(fetch).toHaveBeenCalledWith('https://school.magister.net/api/personen/17/cijfers/laatste?top=25&skip=0',expect.objectContaining({headers:{Authorization:'synthetic-'+'token'},credentials:'omit',redirect:'error'}));
 let finish!:(response:Response)=>void;fetch.mockImplementationOnce(()=>new Promise(resolve=>{finish=resolve;}));
 const pending=send();capture({...request,url:request.url.replace('/17/','/18/')});finish(new Response(JSON.stringify({items:[]}),{status:200}));
 expect(await pending).toMatchObject({ok:false});expect(await send()).toMatchObject({ok:false});complete({requestId:request.requestId,statusCode:200} as chrome.webRequest.OnCompletedDetails);expect(await send()).toMatchObject({userId:'18'});
 navigate({tabId:1} as chrome.webRequest.OnBeforeRequestDetails);expect(await send()).toMatchObject({ok:false});
 capture(request);complete({requestId:request.requestId,statusCode:401} as chrome.webRequest.OnCompletedDetails);expect(await send()).toMatchObject({ok:false});
 capture(request);complete({requestId:request.requestId,statusCode:200} as chrome.webRequest.OnCompletedDetails);expect(await send()).toMatchObject({ok:true});
 capture(request);removed(1);expect(await send()).toMatchObject({ok:false});expect(storage).not.toHaveBeenCalled();
});
