import type {MatchExplanation} from '../somtoday/dom-join';
type Stage='document-start'|'static-css'|'owner-mount'|'classification'|'safe-presentation';
const entries:{time:number;component:string;concealed:boolean;route:string;stage:Stage}[]=[];
const cards=new Map<string,MatchExplanation>();let host:HTMLElement|null=null;let reportNode:HTMLElement|null=null;let open=false;
const safeText=(value:string)=>[...value.normalize('NFKC')].filter(c=>{const n=c.charCodeAt(0);return n>=32&&n!==127;}).join('').slice(0,240);
function render(){if(!reportNode)return;reportNode.textContent=JSON.stringify({cards:[...cards.values()]},null,2);}
function mount(){if(host?.isConnected)return;host=document.createElement('div');host.id='po-developer-debug';const shadow=host.attachShadow({mode:'closed'});const style=document.createElement('style');style.textContent=`:host{all:initial;position:fixed;right:18px;bottom:18px;z-index:2147483646;color:#e2e6e9;font:13px/1.45 "Open Sans",system-ui,sans-serif;color-scheme:dark}button{font:inherit;color:inherit;cursor:pointer}.toggle{border:1px solid #46525b;border-radius:10px;background:#20272c;padding:9px 13px;box-shadow:0 8px 28px #0008}.panel{display:none;width:min(430px,calc(100vw - 36px));max-height:min(70vh,620px);margin-bottom:8px;border:1px solid #46525b;border-radius:12px;background:#171c20;box-shadow:0 16px 44px #0009;overflow:hidden}.panel[data-open="true"]{display:flex;flex-direction:column}.head{display:flex;align-items:center;justify-content:space-between;padding:12px 14px;border-bottom:1px solid #30383e}.actions{display:flex;gap:8px}.actions button{border:1px solid #46525b;border-radius:7px;background:#242c31;padding:5px 8px}.hint{padding:8px 14px;color:#aeb8c0;font-size:11px}pre{margin:0;padding:12px 14px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;font:11px/1.45 ui-monospace,Consolas,monospace;color:#d4dce1}button:focus-visible{outline:2px solid #80b5ed;outline-offset:2px}`;shadow.append(style);const panel=document.createElement('section');panel.className='panel';panel.setAttribute('data-open','false');panel.setAttribute('aria-label','Live debugdiagnostiek');const head=document.createElement('div');head.className='head';const title=document.createElement('strong');title.textContent='Debug · cijferkoppeling';const actions=document.createElement('div');actions.className='actions';const copy=document.createElement('button');copy.textContent='Kopieer debugrapport';copy.addEventListener('click',()=>{void navigator.clipboard.writeText(reportNode?.textContent??'').then(()=>{copy.textContent='Gekopieerd';setTimeout(()=>copy.textContent='Kopieer debugrapport',1400);}).catch(()=>{copy.textContent='Kopiëren mislukt';});});const close=document.createElement('button');close.textContent='Sluiten';close.addEventListener('click',()=>{open=false;panel.dataset.open='false';toggle.setAttribute('aria-expanded','false');});actions.append(copy,close);head.append(title,actions);const hint=document.createElement('div');hint.className='hint';hint.textContent='Geen cijfers, account-ID’s, cookies of tokens worden getoond.';reportNode=document.createElement('pre');panel.append(head,hint,reportNode);const toggle=document.createElement('button');toggle.className='toggle';toggle.textContent='Debug';toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-controls','po-debug-panel');panel.id='po-debug-panel';toggle.addEventListener('click',()=>{open=!open;panel.dataset.open=String(open);toggle.setAttribute('aria-expanded',String(open));if(open)render();});shadow.append(panel,toggle);document.documentElement.append(host);}
export function diagnosticStage(stage:Stage,component:string,concealed:boolean){if(!import.meta.env.DEV)return;entries.push({time:Math.round(performance.now()),component,concealed,route:['/cijfers','/cijfers/overzicht','/cijfers/vakgemiddelden','/cijfers/vakresultaten','/rooster'].includes(location.pathname)?location.pathname:'overige route',stage});if(entries.length>200)entries.shift();}
export function updateCardDiagnostic(owner:HTMLElement,data:MatchExplanation){if(!import.meta.env.DEV)return;mount();const key=owner.dataset.poDebugKey??`kaart-${cards.size+1}`;owner.dataset.poDebugKey=key;cards.set(key,{...data,dom:{...data.dom,subject:safeText(data.dom.subject),description:safeText(data.dom.description),normalizedDate:safeText(data.dom.normalizedDate),weight:safeText(data.dom.weight)},candidates:data.candidates.map(c=>({...c,subject:safeText(c.subject),description:safeText(c.description),normalizedDate:safeText(c.normalizedDate),weight:safeText(c.weight),testCode:safeText(c.testCode),columnId:c.columnId?safeText(c.columnId):null,logicalIdentity:safeText(c.logicalIdentity)}))});render();}
export function diagnose(owner:HTMLElement){diagnosticStage('owner-mount',owner.tagName.toLowerCase(),isConcealed(owner));}
export function isConcealed(owner:HTMLElement){const style=getComputedStyle(owner),root=owner.querySelector<HTMLElement>('.root'),grade=owner.querySelector<HTMLElement>('.cijfer');return owner.inert||owner.getAttribute('aria-hidden')==='true'||style.display==='none'||style.visibility==='hidden'||!!root&&getComputedStyle(root).visibility==='hidden'||!!grade&&getComputedStyle(grade).visibility==='hidden';}
export function diagnosticReport(){const css=entries.find(x=>x.stage==='static-css'),mount=entries.find(x=>x.stage==='owner-mount');return {status:css&&mount&&css.time<=mount.time&&entries.every(x=>x.concealed)?'success':'failure',entries:[...entries]};}
